{% set num_categories = 15505 %}


runtime:
  timestamp: {{ timestamp }}
  run_id: {{ run_id }}
  run_dir: {{ run_dir }}
  use_gpu: {{ use_gpu | default(true) }}
  use_amp: {{ use_amp | default(true) }}
  num_workers: {{ num_workers }}
  time_limit: {{ time_limit }}
  num_epochs: {{ num_epochs }}
  batch_size: {{ batch_size }}
  batch_limit: {{ batch_limit }}
  random_seed: {{ random_seed | default(1657964356) }}
  command_hash: {{ command_hash | default("none")}}
  snapshots:
    enabled: true
    start: 6
    rate: 1
  save_best:
    enabled: true
    start: 10


model:
  __target__: herbarium.model.mobilenet_v3_small
  num_categories: {{ num_categories }}
  use_gpu: {{ use_gpu | default(true) }}
  pretrained: true


optimizer:
  __target__: herbarium.optim.AdamW
  model:
    __instance__: model
  lr: {{ learning_rate | default(0.0001) }}
  weight_decay: {{ weight_decay | default(0.01) }}

log_writer:
  __target__: herbarium.nodes.logger.LogWriter
  log_dir: {{ run_dir }}

  
train_pipeline:
  - __target__: herbarium.nodes.data.HerbariumDataset
    dsroot: ~/Projects/datasets/fgvc9-herbarium-2022
    image_dir: train_images_500
    split: train
    batch_size: {{ batch_size }}
  - __target__: herbarium.nodes.data.BatchLimiter
    batch_limit: {{ batch_limit }}
    batch_size: {{ batch_size }}
  - __target__: herbarium.nodes.data.AlbumentationsTransformer
    transforms:
      - __target__: albumentations.Flip
        p: 0.666
      - __target__: albumentations.Resize
        height: 500
        width: 500
        p: 1.0
      - __target__: albumentations.RandomCrop
        height: 336 
        width: 336
        p: 1.0
      - __target__: albumentations.GaussNoise
        p: {{ gauss_noise_p | default(1.0) }}
      - __target__: albumentations.CoarseDropout
        fill_value: 175
        min_holes: 16
        max_holes: 32
        min_width: 8
        max_width: 24
        min_height: 8
        max_height: 24
        p: {{ coarse_dropout_p | default(0.0) }}
      - __target__: albumentations.Normalize
        mean: [0.7786, 0.7569, 0.7102]
        std: [0.2468, 0.2507, 0.2537]
      - __target__: albumentations.pytorch.ToTensorV2
  - __target__: herbarium.nodes.data.DataLoader
    num_workers: {{ num_workers | default(0) }}
    batch_size: {{ batch_size }}
    drop_last: true
    pin_memory: {{ use_gpu | default(true) }}
  - __target__: herbarium.nodes.train.Trainer
    model:
      __instance__: model
    criterion:
      __target__: torch.nn.CrossEntropyLoss
    optimizer:
      __instance__: optimizer
    use_amp: {{ use_amp | default(true) }}
  - __target__: herbarium.nodes.scheduler.OneCycleCosine
    optimizer:
      __instance__: optimizer
    batch_mode: true
    peak_epoch: {{ peak_epoch | default(2) }}
    final_epoch: {{ final_epoch | default(10) }}
    peak_scale: {{ peak_scale | default(10) }}
    final_scale: {{ final_scale | default(0.1) }}
  - __target__: herbarium.nodes.evaluate.F1Score
    num_categories: {{ num_categories }}
  - __target__: herbarium.nodes.logger.Logger
    prefix: Train
    writer:
      __instance__: log_writer


validate_pipeline:
  - __target__: herbarium.nodes.data.HerbariumDataset
    dsroot: ~/Projects/datasets/fgvc9-herbarium-2022
    image_dir: train_images_500
    split: val
    batch_size: {{ batch_size }}
  - __target__: herbarium.nodes.data.BatchLimiter
    batch_limit: {{ batch_limit }}
    batch_size: {{ batch_size }}
  - __target__: herbarium.nodes.data.AlbumentationsTransformer
    transforms:
      - __target__: albumentations.Resize
        height: 500
        width: 500
      - __target__: albumentations.CenterCrop
        height: 336 
        width: 336
      - __target__: albumentations.Normalize
        mean: [0.7786, 0.7569, 0.7102]
        std: [0.2468, 0.2507, 0.2537]
      - __target__: albumentations.pytorch.ToTensorV2
  - __target__: herbarium.nodes.data.DataLoader
    num_workers: {{ num_workers | default(0) }}
    batch_size: {{ batch_size }}
    drop_last: false
    pin_memory: {{ use_gpu | default(true) }}
  - __target__: herbarium.nodes.validate.Validator
    model:
      __instance__: model
    criterion:
      __target__: torch.nn.CrossEntropyLoss
    use_amp: false
  - __target__: herbarium.nodes.evaluate.F1Score
    num_categories: {{ num_categories }}
  - __target__: herbarium.nodes.logger.Logger
    prefix: Vdate
    writer:
      __instance__: log_writer

